# render.yaml

services:
  - type: static
    name: my-react-app
    env: static
    buildCommand: npm run build
    publishPath: build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
        status: 200
